//go:build go1.22

// Package webapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package webapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ActionKind.
const (
	AdoptCandidatesAsNotes ActionKind = "adopt-candidates-as-notes"
	ApplyHint              ActionKind = "apply-hint"
	ClearValue             ActionKind = "clear-value"
	Redo                   ActionKind = "redo"
	Repair                 ActionKind = "repair"
	Reset                  ActionKind = "reset"
	SetNotes               ActionKind = "set-notes"
	SetValue               ActionKind = "set-value"
	Solve                  ActionKind = "solve"
	Undo                   ActionKind = "undo"
)

// Defines values for Difficulty.
const (
	Easy   Difficulty = "easy"
	Evil   Difficulty = "evil"
	Expert Difficulty = "expert"
	Hard   Difficulty = "hard"
	Medium Difficulty = "medium"
)

// Defines values for ErrorCode.
const (
	ErrorCodeForbiddenOrigin      ErrorCode = "forbidden-origin"
	ErrorCodeImmutableCell        ErrorCode = "immutable-cell"
	ErrorCodeInternalError        ErrorCode = "internal-error"
	ErrorCodeInvalidAction        ErrorCode = "invalid-action"
	ErrorCodeInvalidCell          ErrorCode = "invalid-cell"
	ErrorCodeInvalidJson          ErrorCode = "invalid-json"
	ErrorCodeInvalidRequest       ErrorCode = "invalid-request"
	ErrorCodeInvalidSession       ErrorCode = "invalid-session"
	ErrorCodeNoHint               ErrorCode = "no-hint"
	ErrorCodeNoRedo               ErrorCode = "no-redo"
	ErrorCodeNoUndo               ErrorCode = "no-undo"
	ErrorCodeNoteNotAllowed       ErrorCode = "note-not-allowed"
	ErrorCodePayloadTooLarge      ErrorCode = "payload-too-large"
	ErrorCodePersistenceFailed    ErrorCode = "persistence-failed"
	ErrorCodeRevisionConflict     ErrorCode = "revision-conflict"
	ErrorCodeSessionNotFound      ErrorCode = "session-not-found"
	ErrorCodeUnauthorized         ErrorCode = "unauthorized"
	ErrorCodeUnsupportedMediaType ErrorCode = "unsupported-media-type"
)

// Defines values for GameStatus.
const (
	InProgress GameStatus = "in-progress"
	Invalid    GameStatus = "invalid"
	Solved     GameStatus = "solved"
)

// ActionKind defines model for ActionKind.
type ActionKind string

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	union json.RawMessage
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	Result   ActionResult `json:"result"`
	Revision Revision     `json:"revision"`
	Snapshot Snapshot     `json:"snapshot"`

	// Warnings Non-fatal diagnostics produced after the game action was accepted.
	Warnings *[]string `json:"warnings,omitempty"`
}

// ActionResult defines model for ActionResult.
type ActionResult struct {
	Action  ActionKind   `json:"action"`
	CanRedo bool         `json:"can_redo"`
	CanUndo bool         `json:"can_undo"`
	Changes []CellChange `json:"changes"`
	Hint    *Hint        `json:"hint,omitempty"`
	Status  GameStatus   `json:"status"`
}

// AdoptCandidatesAsNotesAction defines model for AdoptCandidatesAsNotesAction.
type AdoptCandidatesAsNotesAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Value            Digit    `json:"value"`
}

// ApplyHintAction defines model for ApplyHintAction.
type ApplyHintAction = NoArgumentApplyHintAction

// BooleanGrid defines model for BooleanGrid.
type BooleanGrid = []BooleanRow

// BooleanRow defines model for BooleanRow.
type BooleanRow = []bool

// CellChange defines model for CellChange.
type CellChange struct {
	// After Zero represents an empty cell.
	After CellValue `json:"after"`

	// Before Zero represents an empty cell.
	Before        CellValue `json:"before"`
	Column        int       `json:"column"`
	InvalidAfter  bool      `json:"invalid_after"`
	InvalidBefore bool      `json:"invalid_before"`
	NotesAfter    DigitSet  `json:"notes_after"`
	NotesBefore   DigitSet  `json:"notes_before"`
	Row           int       `json:"row"`
}

// CellPosition defines model for CellPosition.
type CellPosition struct {
	Column int `json:"column"`
	Row    int `json:"row"`
}

// CellValue Zero represents an empty cell.
type CellValue = int

// ClearValueAction defines model for ClearValueAction.
type ClearValueAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Source CreateSessionRequest_Source `json:"source"`
}

// CreateSessionRequest_Source defines model for CreateSessionRequest.Source.
type CreateSessionRequest_Source struct {
	union json.RawMessage
}

// Difficulty defines model for Difficulty.
type Difficulty string

// DifficultySource defines model for DifficultySource.
type DifficultySource struct {
	Difficulty Difficulty `json:"difficulty"`
	Kind       string     `json:"kind"`
}

// Digit defines model for Digit.
type Digit = int

// DigitSet defines model for DigitSet.
type DigitSet = []Digit

// DigitSetGrid defines model for DigitSetGrid.
type DigitSetGrid = []DigitSetRow

// DigitSetRow defines model for DigitSetRow.
type DigitSetRow = []DigitSet

// Error defines model for Error.
type Error struct {
	Error ErrorDetail `json:"error"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Cell    *CellPosition `json:"cell,omitempty"`
	Code    ErrorCode     `json:"code"`
	Field   *string       `json:"field,omitempty"`
	Message string        `json:"message"`
}

// GameStatus defines model for GameStatus.
type GameStatus string

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Hint defines model for Hint.
type Hint struct {
	Column    int    `json:"column"`
	Reason    string `json:"reason"`
	Row       int    `json:"row"`
	Technique string `json:"technique"`
	Value     Digit  `json:"value"`
}

// HintPreview defines model for HintPreview.
type HintPreview struct {
	Hint     Hint     `json:"hint"`
	Revision Revision `json:"revision"`
}

// NoArgumentApplyHintAction defines model for NoArgumentApplyHintAction.
type NoArgumentApplyHintAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentRedoAction defines model for NoArgumentRedoAction.
type NoArgumentRedoAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentRepairAction defines model for NoArgumentRepairAction.
type NoArgumentRepairAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentResetAction defines model for NoArgumentResetAction.
type NoArgumentResetAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentSolveAction defines model for NoArgumentSolveAction.
type NoArgumentSolveAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// NoArgumentUndoAction defines model for NoArgumentUndoAction.
type NoArgumentUndoAction struct {
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
}

// PuzzleSource defines model for PuzzleSource.
type PuzzleSource struct {
	Kind string `json:"kind"`

	// Puzzle An 81-cell puzzle; dot or zero represents an empty cell.
	Puzzle string `json:"puzzle"`
}

// RedoAction defines model for RedoAction.
type RedoAction = NoArgumentRedoAction

// RepairAction defines model for RepairAction.
type RepairAction = NoArgumentRepairAction

// ResetAction defines model for ResetAction.
type ResetAction = NoArgumentResetAction

// Revision defines model for Revision.
type Revision = int64

// RevisionConflict defines model for RevisionConflict.
type RevisionConflict struct {
	CurrentRevision Revision `json:"current_revision"`
	Error           struct {
		Cell    *CellPosition `json:"cell,omitempty"`
		Code    string        `json:"code"`
		Field   *string       `json:"field,omitempty"`
		Message string        `json:"message"`
	} `json:"error"`
	Snapshot Snapshot `json:"snapshot"`
}

// Session defines model for Session.
type Session struct {
	Id       SessionId `json:"id"`
	Revision Revision  `json:"revision"`
	Snapshot Snapshot  `json:"snapshot"`
}

// SessionId defines model for SessionId.
type SessionId = string

// SessionList defines model for SessionList.
type SessionList struct {
	Sessions []SessionSummary `json:"sessions"`
}

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Id SessionId `json:"id"`

	// Recovered True when the summary was discovered from durable recovery at startup.
	Recovered bool       `json:"recovered"`
	Revision  Revision   `json:"revision"`
	Status    GameStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// SetNotesAction defines model for SetNotesAction.
type SetNotesAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Values           DigitSet `json:"values"`
}

// SetValueAction defines model for SetValueAction.
type SetValueAction struct {
	Column           int      `json:"column"`
	ExpectedRevision Revision `json:"expected_revision"`
	Kind             string   `json:"kind"`
	Row              int      `json:"row"`
	Value            Digit    `json:"value"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	CanRedo    bool         `json:"can_redo"`
	CanUndo    bool         `json:"can_undo"`
	Candidates DigitSetGrid `json:"candidates"`
	Givens     ValueGrid    `json:"givens"`
	Invalid    BooleanGrid  `json:"invalid"`

	// Mistakes Count of server-confirmed invalid value submissions in this session.
	Mistakes int          `json:"mistakes"`
	Notes    DigitSetGrid `json:"notes"`
	Status   GameStatus   `json:"status"`
	Values   ValueGrid    `json:"values"`
}

// SolveAction defines model for SolveAction.
type SolveAction = NoArgumentSolveAction

// UndoAction defines model for UndoAction.
type UndoAction = NoArgumentUndoAction

// ValueGrid defines model for ValueGrid.
type ValueGrid = []ValueRow

// ValueRow defines model for ValueRow.
type ValueRow = []CellValue

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = Error

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = Error

// ImportSessionApplicationVndSudokuSessionPlusJSONBody defines parameters for ImportSession.
type ImportSessionApplicationVndSudokuSessionPlusJSONBody = openapi_types.File

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody defines body for ImportSession for application/vnd.sudoku.session+json ContentType.
type ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody = ImportSessionApplicationVndSudokuSessionPlusJSONBody

// ApplyActionJSONRequestBody defines body for ApplyAction for application/json ContentType.
type ApplyActionJSONRequestBody = ActionRequest

// AsSetValueAction returns the union data inside the ActionRequest as a SetValueAction
func (t ActionRequest) AsSetValueAction() (SetValueAction, error) {
	var body SetValueAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetValueAction overwrites any union data inside the ActionRequest as the provided SetValueAction
func (t *ActionRequest) FromSetValueAction(v SetValueAction) error {
	v.Kind = "set-value"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetValueAction performs a merge with any union data inside the ActionRequest, using the provided SetValueAction
func (t *ActionRequest) MergeSetValueAction(v SetValueAction) error {
	v.Kind = "set-value"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClearValueAction returns the union data inside the ActionRequest as a ClearValueAction
func (t ActionRequest) AsClearValueAction() (ClearValueAction, error) {
	var body ClearValueAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClearValueAction overwrites any union data inside the ActionRequest as the provided ClearValueAction
func (t *ActionRequest) FromClearValueAction(v ClearValueAction) error {
	v.Kind = "clear-value"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClearValueAction performs a merge with any union data inside the ActionRequest, using the provided ClearValueAction
func (t *ActionRequest) MergeClearValueAction(v ClearValueAction) error {
	v.Kind = "clear-value"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResetAction returns the union data inside the ActionRequest as a ResetAction
func (t ActionRequest) AsResetAction() (ResetAction, error) {
	var body ResetAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResetAction overwrites any union data inside the ActionRequest as the provided ResetAction
func (t *ActionRequest) FromResetAction(v ResetAction) error {
	v.Kind = "reset"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResetAction performs a merge with any union data inside the ActionRequest, using the provided ResetAction
func (t *ActionRequest) MergeResetAction(v ResetAction) error {
	v.Kind = "reset"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUndoAction returns the union data inside the ActionRequest as a UndoAction
func (t ActionRequest) AsUndoAction() (UndoAction, error) {
	var body UndoAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUndoAction overwrites any union data inside the ActionRequest as the provided UndoAction
func (t *ActionRequest) FromUndoAction(v UndoAction) error {
	v.Kind = "undo"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUndoAction performs a merge with any union data inside the ActionRequest, using the provided UndoAction
func (t *ActionRequest) MergeUndoAction(v UndoAction) error {
	v.Kind = "undo"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRedoAction returns the union data inside the ActionRequest as a RedoAction
func (t ActionRequest) AsRedoAction() (RedoAction, error) {
	var body RedoAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRedoAction overwrites any union data inside the ActionRequest as the provided RedoAction
func (t *ActionRequest) FromRedoAction(v RedoAction) error {
	v.Kind = "redo"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRedoAction performs a merge with any union data inside the ActionRequest, using the provided RedoAction
func (t *ActionRequest) MergeRedoAction(v RedoAction) error {
	v.Kind = "redo"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApplyHintAction returns the union data inside the ActionRequest as a ApplyHintAction
func (t ActionRequest) AsApplyHintAction() (ApplyHintAction, error) {
	var body ApplyHintAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApplyHintAction overwrites any union data inside the ActionRequest as the provided ApplyHintAction
func (t *ActionRequest) FromApplyHintAction(v ApplyHintAction) error {
	v.Kind = "apply-hint"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApplyHintAction performs a merge with any union data inside the ActionRequest, using the provided ApplyHintAction
func (t *ActionRequest) MergeApplyHintAction(v ApplyHintAction) error {
	v.Kind = "apply-hint"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSetNotesAction returns the union data inside the ActionRequest as a SetNotesAction
func (t ActionRequest) AsSetNotesAction() (SetNotesAction, error) {
	var body SetNotesAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSetNotesAction overwrites any union data inside the ActionRequest as the provided SetNotesAction
func (t *ActionRequest) FromSetNotesAction(v SetNotesAction) error {
	v.Kind = "set-notes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSetNotesAction performs a merge with any union data inside the ActionRequest, using the provided SetNotesAction
func (t *ActionRequest) MergeSetNotesAction(v SetNotesAction) error {
	v.Kind = "set-notes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAdoptCandidatesAsNotesAction returns the union data inside the ActionRequest as a AdoptCandidatesAsNotesAction
func (t ActionRequest) AsAdoptCandidatesAsNotesAction() (AdoptCandidatesAsNotesAction, error) {
	var body AdoptCandidatesAsNotesAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAdoptCandidatesAsNotesAction overwrites any union data inside the ActionRequest as the provided AdoptCandidatesAsNotesAction
func (t *ActionRequest) FromAdoptCandidatesAsNotesAction(v AdoptCandidatesAsNotesAction) error {
	v.Kind = "adopt-candidates-as-notes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAdoptCandidatesAsNotesAction performs a merge with any union data inside the ActionRequest, using the provided AdoptCandidatesAsNotesAction
func (t *ActionRequest) MergeAdoptCandidatesAsNotesAction(v AdoptCandidatesAsNotesAction) error {
	v.Kind = "adopt-candidates-as-notes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRepairAction returns the union data inside the ActionRequest as a RepairAction
func (t ActionRequest) AsRepairAction() (RepairAction, error) {
	var body RepairAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRepairAction overwrites any union data inside the ActionRequest as the provided RepairAction
func (t *ActionRequest) FromRepairAction(v RepairAction) error {
	v.Kind = "repair"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRepairAction performs a merge with any union data inside the ActionRequest, using the provided RepairAction
func (t *ActionRequest) MergeRepairAction(v RepairAction) error {
	v.Kind = "repair"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolveAction returns the union data inside the ActionRequest as a SolveAction
func (t ActionRequest) AsSolveAction() (SolveAction, error) {
	var body SolveAction
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolveAction overwrites any union data inside the ActionRequest as the provided SolveAction
func (t *ActionRequest) FromSolveAction(v SolveAction) error {
	v.Kind = "solve"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolveAction performs a merge with any union data inside the ActionRequest, using the provided SolveAction
func (t *ActionRequest) MergeSolveAction(v SolveAction) error {
	v.Kind = "solve"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ActionRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ActionRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "adopt-candidates-as-notes":
		return t.AsAdoptCandidatesAsNotesAction()
	case "apply-hint":
		return t.AsApplyHintAction()
	case "clear-value":
		return t.AsClearValueAction()
	case "redo":
		return t.AsRedoAction()
	case "repair":
		return t.AsRepairAction()
	case "reset":
		return t.AsResetAction()
	case "set-notes":
		return t.AsSetNotesAction()
	case "set-value":
		return t.AsSetValueAction()
	case "solve":
		return t.AsSolveAction()
	case "undo":
		return t.AsUndoAction()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ActionRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ActionRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsDifficultySource returns the union data inside the CreateSessionRequest_Source as a DifficultySource
func (t CreateSessionRequest_Source) AsDifficultySource() (DifficultySource, error) {
	var body DifficultySource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDifficultySource overwrites any union data inside the CreateSessionRequest_Source as the provided DifficultySource
func (t *CreateSessionRequest_Source) FromDifficultySource(v DifficultySource) error {
	v.Kind = "difficulty"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDifficultySource performs a merge with any union data inside the CreateSessionRequest_Source, using the provided DifficultySource
func (t *CreateSessionRequest_Source) MergeDifficultySource(v DifficultySource) error {
	v.Kind = "difficulty"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPuzzleSource returns the union data inside the CreateSessionRequest_Source as a PuzzleSource
func (t CreateSessionRequest_Source) AsPuzzleSource() (PuzzleSource, error) {
	var body PuzzleSource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPuzzleSource overwrites any union data inside the CreateSessionRequest_Source as the provided PuzzleSource
func (t *CreateSessionRequest_Source) FromPuzzleSource(v PuzzleSource) error {
	v.Kind = "puzzle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePuzzleSource performs a merge with any union data inside the CreateSessionRequest_Source, using the provided PuzzleSource
func (t *CreateSessionRequest_Source) MergePuzzleSource(v PuzzleSource) error {
	v.Kind = "puzzle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateSessionRequest_Source) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CreateSessionRequest_Source) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "difficulty":
		return t.AsDifficultySource()
	case "puzzle":
		return t.AsPuzzleSource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CreateSessionRequest_Source) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateSessionRequest_Source) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List active and recovered sessions
	// (GET /api/v1/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a session from a difficulty or puzzle
	// (POST /api/v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Import a serialized game session
	// (POST /api/v1/sessions/import)
	ImportSession(w http.ResponseWriter, r *http.Request)
	// Discard a session and its recovery record
	// (DELETE /api/v1/sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Read the authoritative session state
	// (GET /api/v1/sessions/{sessionId})
	GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Apply one typed game action
	// (POST /api/v1/sessions/{sessionId}/actions)
	ApplyAction(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Export the versioned serialized session
	// (GET /api/v1/sessions/{sessionId}/export)
	ExportSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Preview a hint without mutating the session
	// (GET /api/v1/sessions/{sessionId}/hint)
	PreviewHint(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Check process health
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ImportSession operation middleware
func (siw *ServerInterfaceWrapper) ImportSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ImportSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyAction(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportSession operation middleware
func (siw *ServerInterfaceWrapper) ExportSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewHint operation middleware
func (siw *ServerInterfaceWrapper) PreviewHint(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewHint(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions", wrapper.ListSessions)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions", wrapper.CreateSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions/import", wrapper.ImportSession)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.GetSession)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/sessions/{sessionId}/actions", wrapper.ApplyAction)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}/export", wrapper.ExportSession)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/sessions/{sessionId}/hint", wrapper.PreviewHint)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)

	return m
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type PayloadTooLargeJSONResponse Error

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedJSONResponse struct {
	Body Error

	Headers UnauthorizedResponseHeaders
}

type UnprocessableEntityJSONResponse Error

type UnsupportedMediaTypeJSONResponse Error

type ListSessionsRequestObject struct {
}

type ListSessionsResponseObject interface {
	VisitListSessionsResponse(w http.ResponseWriter) error
}

type ListSessions200JSONResponse SessionList

func (response ListSessions200JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSessions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSessions401JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ListSessions500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListSessions500JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201ResponseHeaders struct {
	Location string
}

type CreateSession201JSONResponse struct {
	Body    Session
	Headers CreateSession201ResponseHeaders
}

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSession400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSession401JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateSession413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response CreateSession413JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateSession415JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response CreateSession422JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type CreateSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateSession500JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportSessionRequestObject struct {
	Body *ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody
}

type ImportSessionResponseObject interface {
	VisitImportSessionResponse(w http.ResponseWriter) error
}

type ImportSession201ResponseHeaders struct {
	Location string
}

type ImportSession201JSONResponse struct {
	Body    Session
	Headers ImportSession201ResponseHeaders
}

func (response ImportSession201JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type ImportSession400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportSession400JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ImportSession401JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ImportSession413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ImportSession413JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ImportSession415JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ImportSession422JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ImportSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response ImportSession500JSONResponse) VisitImportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteSession401JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type DeleteSession404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSession404JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteSession500JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type GetSessionResponseObject interface {
	VisitGetSessionResponse(w http.ResponseWriter) error
}

type GetSession200JSONResponse Session

func (response GetSession200JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSession401JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetSession404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSession404JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSession500JSONResponse) VisitGetSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyActionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
	Body      *ApplyActionJSONRequestBody
}

type ApplyActionResponseObject interface {
	VisitApplyActionResponse(w http.ResponseWriter) error
}

type ApplyAction200JSONResponse ActionResponse

func (response ApplyAction200JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction400JSONResponse struct{ BadRequestJSONResponse }

func (response ApplyAction400JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ApplyAction401JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ApplyAction404JSONResponse struct{ NotFoundJSONResponse }

func (response ApplyAction404JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction409JSONResponse RevisionConflict

func (response ApplyAction409JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction413JSONResponse struct{ PayloadTooLargeJSONResponse }

func (response ApplyAction413JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response ApplyAction415JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response ApplyAction422JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction500JSONResponse struct{ InternalErrorJSONResponse }

func (response ApplyAction500JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExportSessionRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type ExportSessionResponseObject interface {
	VisitExportSessionResponse(w http.ResponseWriter) error
}

type ExportSession200ResponseHeaders struct {
	ContentDisposition string
}

type ExportSession200ApplicationVndSudokuSessionPlusJSONResponse struct {
	Body    openapi_types.File
	Headers ExportSession200ResponseHeaders
}

func (response ExportSession200ApplicationVndSudokuSessionPlusJSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.sudoku.session+json")
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExportSession401JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type ExportSession404JSONResponse struct{ NotFoundJSONResponse }

func (response ExportSession404JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ExportSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportSession500JSONResponse) VisitExportSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHintRequestObject struct {
	SessionId SessionId `json:"sessionId"`
}

type PreviewHintResponseObject interface {
	VisitPreviewHintResponse(w http.ResponseWriter) error
}

type PreviewHint200JSONResponse HintPreview

func (response PreviewHint200JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PreviewHint401JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type PreviewHint404JSONResponse struct{ NotFoundJSONResponse }

func (response PreviewHint404JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response PreviewHint422JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PreviewHint500JSONResponse struct{ InternalErrorJSONResponse }

func (response PreviewHint500JSONResponse) VisitPreviewHintResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth400JSONResponse struct{ BadRequestJSONResponse }

func (response GetHealth400JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetHealth500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetHealth500JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List active and recovered sessions
	// (GET /api/v1/sessions)
	ListSessions(ctx context.Context, request ListSessionsRequestObject) (ListSessionsResponseObject, error)
	// Create a session from a difficulty or puzzle
	// (POST /api/v1/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Import a serialized game session
	// (POST /api/v1/sessions/import)
	ImportSession(ctx context.Context, request ImportSessionRequestObject) (ImportSessionResponseObject, error)
	// Discard a session and its recovery record
	// (DELETE /api/v1/sessions/{sessionId})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// Read the authoritative session state
	// (GET /api/v1/sessions/{sessionId})
	GetSession(ctx context.Context, request GetSessionRequestObject) (GetSessionResponseObject, error)
	// Apply one typed game action
	// (POST /api/v1/sessions/{sessionId}/actions)
	ApplyAction(ctx context.Context, request ApplyActionRequestObject) (ApplyActionResponseObject, error)
	// Export the versioned serialized session
	// (GET /api/v1/sessions/{sessionId}/export)
	ExportSession(ctx context.Context, request ExportSessionRequestObject) (ExportSessionResponseObject, error)
	// Preview a hint without mutating the session
	// (GET /api/v1/sessions/{sessionId}/hint)
	PreviewHint(ctx context.Context, request PreviewHintRequestObject) (PreviewHintResponseObject, error)
	// Check process health
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListSessions operation middleware
func (sh *strictHandler) ListSessions(w http.ResponseWriter, r *http.Request) {
	var request ListSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessions(ctx, request.(ListSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionsResponseObject); ok {
		if err := validResponse.VisitListSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportSession operation middleware
func (sh *strictHandler) ImportSession(w http.ResponseWriter, r *http.Request) {
	var request ImportSessionRequestObject

	var body ImportSessionApplicationVndSudokuSessionPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ImportSession(ctx, request.(ImportSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ImportSessionResponseObject); ok {
		if err := validResponse.VisitImportSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request DeleteSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSession operation middleware
func (sh *strictHandler) GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request GetSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSession(ctx, request.(GetSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSessionResponseObject); ok {
		if err := validResponse.VisitGetSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyAction operation middleware
func (sh *strictHandler) ApplyAction(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request ApplyActionRequestObject

	request.SessionId = sessionId

	var body ApplyActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyAction(ctx, request.(ApplyActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyActionResponseObject); ok {
		if err := validResponse.VisitApplyActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportSession operation middleware
func (sh *strictHandler) ExportSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request ExportSessionRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportSession(ctx, request.(ExportSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportSessionResponseObject); ok {
		if err := validResponse.VisitExportSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewHint operation middleware
func (sh *strictHandler) PreviewHint(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	var request PreviewHintRequestObject

	request.SessionId = sessionId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewHint(ctx, request.(PreviewHintRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewHint")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewHintResponseObject); ok {
		if err := validResponse.VisitPreviewHintResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8XXMTubJ/RTV33854EocAIVv3IQscoA7Lcgm7W3VILiXPtG0dZqRZSZPEpPzfb7Wk",
	"0Wg+HHuSAAfO5YXY1kd/q7vVresoFUUpOHCtouPrqKSSFqBBmk+noBQT/FWGHzJQqWSlZoJHx9FvJf2r",
	"AiIpz0RBlB1IWAZcszkDmZBXmjBFuNCEklSC+YXmSRRHDBcoqV5GccRpAdFxpPxOcSThr4pJyKJjLSuI",
	"I5UuoaAIwk8S5tFx9F97DdB79le118C6Xq9xEVUKrsDg8QvN3sFfFSiNn1LBNXDzJy3LnKUUcdr7l0LE",
	"riO4okWZg/lTSiHtlAyhZPyC5iybSLdYHM0Z5BnCLyqZQhRHBShFF+C/IkWlNFGQQ6oJXNFU5ysiOBBV",
	"laWQGjLyiXEEeldEnxugDJJtlrxfAnGQIeULms+FLCAjQpILJnKqQRG9BKIl5Qo3J0gKSVOdROs4esU1",
	"SE7z5w3WtyeUXWpifwjJogMoU1HlmRGRGRBENQcN90KLE04qDlclpNoSIKsknbGc6RWZU5ZXEohI00pK",
	"yMgl00tRaZID/cT4gtTQK0OWN0L/XVQ8uxtFnIBPuNCTuVmuJStOfy6p1Rg74n5lAjKvppkAuw9cMWWZ",
	"/5auckGz90K8pnIBd0O2tItNtBCT3CwXIltzfyayFYGrFCCzclnQK1ZUBVHsM9y3QoT7pILP2aJC1hsY",
	"clYwS4XfOa30Ukj2Ge7I7ypcKcR+BlSCJPgrWkS7IuqrN3v3If5+NeL2ayywsQ1MKZR0IYmzaWiXl0Az",
	"Z/n//PPPyUkDokGxgSkVHE1p9ItZO4ojvSqNGGvJ+AIBMrQspUgR71kOz7lmerU7SQ0QwBeMwzv4F6QW",
	"r+voguZVh96Q53bdvCp4dPwgjqS4jI6n69hbo6KoNEIxMYNDbqSUox6kS8oXQCgppZjlUBAz0KDh6OOO",
	"lw0wtI8Hp2YdDZeM5igNXgvNYMt+NEmG8/d/DFxCnhN3EMwqTRzGMyCG/JA5wffn0a+QMfreMPRuCuBX",
	"nBS45MQIyaaj4KndaIIb136DX+C+jcGNm5HZiuglU0SUIA26SbC/EcwTI4//YPZQAF4V0fGHSIGeWNmI",
	"ozQHKv0nCQrQW6h4JsxH8x8SdDVZMo4/4WQuNCj8IROlnqSUZygfoCZU+d8klJShyimRX0B03tO92EEX",
	"ODwZQ0IUjFNtWVTQssTByNWNe20g8AlOeOrHn6g3ONru2UZq0wI44iXj2s8JibVh0lMc8geO8LMMFTcM",
	"fweZCAYakm0cir8Gg5FVG8cqaMBuWLbRJdVt4jQSsnlGG0nL5U2j8Uc/1AjXhpG/c0+PdRyVEkVbr95Y",
	"39v6n3EkOPw2j44/bPOzWyCu45uH9xi3bUJI421jW2htW3bnoV0B3Ta+w+aty9+kQNvRCKR1K2CBfKzP",
	"A8tgQyOr/hnD72j+1goFQ3Ge01yBlxNmT2MJqsr1Nvvrt8CxJg67YPXBeTNibhxaWk5LtRRb9zqtx63j",
	"6JJKzvhC9SPVN4JP5lTTnGSMLrhQmqUKD/qsSiEjdK5BGrdwQQsg1MBvHHGaplBqMK4R01CYtXvW1n1B",
	"paSryEaedfj6ocE+QCquKdnYbjFDFye03TWpR/CHeidpO3/+4VQ+pfyjtaMes5kQOVBe/2qtyuCvxmcy",
	"W3vq3GgJIM+fmjk4u6BXr+yso2mXiHFkz4+b10MNNdKiqa627v6CFnBqR3aZRP055DDyawYkCGg1yLeb",
	"lHocH2tHFo9pEw9Fx0/iqGDc/t1QC8PUBUjcvo50P95G3T4xH9war/4m96Mn/sbXHgOq955vAu8ZWzDd",
	"Y1QfSwe8BSOuSVdvMsiojnEfx5v7pXPo/3UjqB0xH0LxF6ujLyTLdlZON+eduGwrp2Vn86GrqMG8cKu+",
	"tdh9ycBOjDSAaMl3sULGHcGtZjAXEkZNuY12urjwowewT556SANRf4zRwY87YWn05xR0M203VMN5IzW7",
	"e/K1FdJtHzsm9RDuEqkDdhv5IaFHJr0Vin0lg3uPxNmEzR+1oWy7M/8EKYiEEgMVrhWhnEBR6pVJWaCr",
	"MgjT/hASPd/8Ozuo2kH2XY+mWx42g+yTQDW4lFEQiI8grrtQ2BK9Z2w+Z2mV69Vmja5HnNZXFGX1+XO+",
	"Mah8a351g+8aLPZ23xaytHc/7zLFUWWI5s8CUjQ5GaBqZXJOGauKKI6WVCIHkbkSj124YPlgEqUH+Tj2",
	"ZS1odiPRkIgH62zzEZxwBjOGyYSe1Sid9YfCrs6E8946h37rnI+jirO/KnA/a1lBsNMo16WeNNp3CSeO",
	"3WzcTv5GbYyrWc/Zmu18BpqyvG/AzAJDMmBmPTVp2kZT+neb9Tcm2RtvTugO3fZ0rj/mQs5YlgGfCMkW",
	"zObC+hditamdpILPc5aGUDRJ9fobH7fVX7jsfi/dj76D2Yfmubg0AHExcWEdFxOXj+WidsZLkIopDTyF",
	"iUvNx907zSGjEbJj5FnqbjG2+aHexfG3GzsIiGH12l9WG91/DXyhl9HxdH/fCK//PICWz9h3Z26b2pFI",
	"A3Cz3JBoBmF6SzYnpRQLCUo17K6zo9kgK14CzRGocYeu37m2v0uzzHbj62YOofTS5TK+tEcK1F3KjOPR",
	"LUJ4DenSWO9byNIdwv/BGD+ExhNhExveooGBy5HcGJOMGu/Wbs4Ymn2HUHkjTuSiKoDr/4BsRoNskML/",
	"hni6w+ILYRhk978pju6S8Qth2dzwfFMk7aXsF8ExvHr5hjja68MvhGNw+/YNUXRu3D1i2IpBx2HWBc6F",
	"2gPnYB2EX/cL146mxnEldsjPJBOaCEk+75D4qU/eo2nrIMaPJdXov0bH0f9+2J88Sc6vj6brn3aNKh24",
	"Q+T6Uc3yj2yMf1wT/C4Aay5kQbX1XR8dRtvSofXUp3XwOdJpr6QErm9FGB/s0zzfIa3WCvvj6170kEGb",
	"yv2ouk/xDiXPb3UPP5iCiPukCdYeYmJQbDeCATZntGON+NeqTOhQhIVpjh3JYMvvm8LID1Fxeng4+/Xx",
	"1Zsn5f+kB3/o148unx2d4BrBGfDosHUGHBy0z4CTyT/p5PP+5MnHyfnffho6otz2r9n45LWduXttgNvq",
	"tCoKKlft5JqNYW8ss/D73UDFeu0vLFOpuAAJAw0T72UF5HIJ3NSaKAuNqTPJmHKzyFyKwpaq50DcYitC",
	"NVGaSl2VScOn4GLwVpI8umoijqoyo2iHqW5ZV/xyolmx3dHsSX9dZhGsHBJxmJ36O66tCMs876mWYkTO",
	"+m71FJvUS3/HV4hhze53X9tyGpxOY5hwlyIwXyW0qxSau511HC3YBfCts4xo1VPqxO9utSz1rIIpTT/B",
	"QGXgU1FxTcScKJAXII1/xEyhvNuJGFoTVc1Mw4TgijBui8PdkZNs9SpdhfA44tzGOu9mDAKCdiTQMcQv",
	"FCbaa5MVsDsg7C3q5X7c/MiPmhVpBGdXp87MGH0r62eNqSv15Vm77oM6BmklmV6d4jqWBbZX6qSyF0f2",
	"099rN0eYjteJFp8ACdU2Je/qdiv08ODCVRRbu0KYClvO5qLV/QWZKTRWCk2JwanpEms4uNS6rPuR5mLA",
	"u1wCOa0y8akiL9+/f0tO3r4icFUK5Vo+TaMf4wtb5Gwbq4gWJBcpzYkWIleE8uyMKyippBryFcmgzMUK",
	"MpLmDCmekPctnNwNr6aaXYBBC80AxGe8licVB01OMW7gndrkjJ/xYL3c3LcqIjjJhShnNP1EZgjDnFa5",
	"TshvphlHSESH6oaehJ5xLvjET7ILgbSNtzRXIhg82HyXkKcWwTOulqYjVQHPCB1onQu5y6SjUAFc1/12",
	"iAAkZyggOUvBVdk3bdHRcfTrq/dN3zN+QFmsg5PopEVUx1LDtDrIIUg/w2UUD6ZNKU+H92jFQVojEk2T",
	"/WTf1OyUwGnJouPoQTJNpubqXi+N5O/Rku1dTPfCyG1hSz66gq4ryRWZiYpnkLlAhoERH2KJI92YutHN",
	"FQgYCfdNVRjVRhhbntZbdpq2D/b3d+hAG9UcbkLZgd4w93OAjJCZCchmK1IIhexNget8RVykQuZMus7Z",
	"w/3ppu09PnutxtJ1HD20yN08qd2QvW7JCaJimhUuINSrpr3QRBh0YfIFnsTn6zgqhY3n25xolay5JnxQ",
	"+heRje3anK3apVgNzC9QL6kGIiRBgTApbKpWxKfJvQMdlr8FJW6unMueduFPhqmz1VufVW92PcXQ2UbW",
	"1HT55QyyG7d0y/shvmAuSR4kB8mjJHmCfz1MkmmSTI+SR4dJkiRH0+TgSZI8Tuy/oyR59Dg5OsC/Dx4l",
	"Tx6arw6SB2b2w2SKf43q+BysKly3D3VXSNVRpOl9K9KmBsuwjz014GaEovbY88DcYXQ6jV8LC8iQqcmt",
	"Ffz93Wv00vEc43AZut4N0EFqq2vL9rbmugw2h7uoZPCSxG1V/3D6YPukbju+mfdwl80G+nhx8sHBLpP7",
	"Hdv3Yaus4KL2OfFwytjoL1qE5q6sb7XWce+E2mMF4ml47yxaV3yUFngiU39YuTOx9RJCau4yrW/TepmA",
	"Gc8JPaL2UMK0gnz+s5FH9LPsoWe7xXC3JR4Yc5aDWikNBcFD1roEbZP7yiAw1uRe8CxR5rRPHGR/66uw",
	"mxu0cvd1Pm4yeDPGkVNxu5jn8Ojh40cDuvJvZG+sDAT8RMPjXE40PTwjBc2gTqneyfR09/p/+/O92B+r",
	"aMb++EcYQpd6d5tz7d8pWluhycG+jdHW7Gfm+1CzW+pxOBy/1TKMUit4vkJD01wC4B8yI5cggdh9s9u7",
	"n4cWhpsn+Ydv7oMHz5hKqcyCQwDRHMBwk9vqopE2oV+A3kjl/a9lhNztpkfMezuIYQaapku0Gi45+z0x",
	"7R3QzNi+dqhfI2rC/YBfL2gBZU5XNswIXhLbcJ3dDAlv0c63KN6erfvuPVc2bpN4g9fw3iRL3LtRnpOl",
	"FBcsw7iw1KxgSrOUpIJbzqcr+46WyBPyHCX5jNet46SotHvgh6cSClO4Y589cSs3T4KlkBD71o09uc64",
	"0jSvO9IVyYEi7bVxpXgAXMVt43I25GSYCtHgdYvbRnXKXfO0HsCpr2+mg7cy+z5QC29Z7OM8Pu46RImr",
	"7xeal3X6qz3wq5nRI+Km9nsoOzkw92c7Ok8ubDAhA68OWOth/JYVqRsSapP/lTyFsQbncP/JvRGuV42z",
	"gXR9ZWWKGM1J/jO9HaPx5olB9DKz8FmLYVu9zd7CVR1o3ZgRRLMWNM408RJtsoWzlQYVu0chTZxkgqOe",
	"1Xp+1Q2NdlbPf4f4qC+lN0Se7ZikfprqGVNl0M7cyVdWi4V90S8Tl9yk0jDe5LSAdlTi3+eKqEY/BDf8",
	"2Y/977PIUqpurkoQ8bNoY4DyXTgtVnaMOIZU7z6/tjE9+sX8lrqPZNCTda0pL23/xBc7jsIumMF3AxFI",
	"c5ejA8+2Nq11lqQxtI3v8RVPmW9pXR3x0HwhpeqnQ62fxxfu2q8rYffoGduOtM8bBekFaNf7disxCl70",
	"q4sQfBPczh6XA2CDLXSMQfFxK9/Wq7ktN93Nb3T84byVp1xC+smDt6ypWDPRYXW+7qxxvY7bV8cfzjG+",
	"sBeblsdtIjyzl5rNRWdzjxjFUSVzd+F7vLc3PXic7Cf7yfT4aP9o38QtDpzuos6HmcwlQB8Hd91YMybu",
	"geRqDtuBXuvesVnF28v+Oqc+BqaZvRLENSbuwrmO3PxKXi/W5+v/CwAA///LIs7qi1oAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
